language: swift

osx_image: xcode9.2

before_install: 
  - bundle install
  - bundle exec pod install --project-directory=SwiftMarkdown

script: "xcodebuild test \
  -workspace SwiftMarkdown/SwiftMarkdown.xcworkspace \
  -scheme SwiftMarkdownTests \
  -sdk iphonesimulator11.2 \
  -destination 'name=iPhone 8 Plus'"